blank_issues_enabled: true
contact_links:
  - name: Contact the developer
    url: https://go.rafaelurben.ch/devmail
    about: Please contact me via email if you have any questions or if you found a security issue.
