theme: jekyll-theme-cayman
url: https://www.rafaelurben.ch/django-kmuhelper
baseurl: /django-kmuhelper
title: django-kmuhelper
description: Ein Helfer für Schweizer KMU mit QR-Rechnungen
app:
    title: KMUHelper Dokumenation
    short_title: KMUH Docs
    description: Dokumentation zum KMUHelper
kontakt_url: https://www.rafaelurben.ch/kmuhelper/kontakt
