# Generated by Django 3.0.4 on 2020-04-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kmuhelper', '0004_kunde_zusammenfuegen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunde',
            name='zusammenfuegen',
            field=models.ForeignKey(blank=True, help_text='Dies kann nicht widerrufen werden! Werte im aktuellen Kunden werden bevorzugt.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kmuhelper.Kunde', verbose_name='Zusammenfügen mit'),
        ),
    ]
