# Generated by Django 3.0.4 on 2020-07-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmuhelper', '0021_versandliste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='versandliste',
        ),
        migrations.CreateModel(
            name='ToDoVersand',
            fields=[
            ],
            options={
                'verbose_name': 'ToDo Versand',
                'verbose_name_plural': 'ToDo Versand',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kmuhelper.bestellung',),
        ),
    ]
