# Generated by Django 3.2 on 2021-04-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmuhelper', '0055_auto_20210403_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extradaten'),
        ),
        migrations.AlterField(
            model_name='email',
            name='html_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Daten'),
        ),
    ]
