# Generated by Django 3.2 on 2021-04-12 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kmuhelper', '0058_emailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token'),
        ),
    ]
