# Generated by Django 4.1.5 on 2023-02-05 00:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "kmuhelper",
            "0088_alter_bestellung_bezahlt_alter_bestellung_versendet_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="einstellung",
            name="description",
        ),
        migrations.RemoveField(
            model_name="einstellung",
            name="name",
        ),
    ]
