# Generated by Django 4.1.6 on 2023-02-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmuhelper', '0091_rename_fix_summe_bestellung_cached_sum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestellungskosten',
            old_name='rabatt',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='bestellungskosten',
            old_name='preis',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='bestellungskosten',
            old_name='mwstsatz',
            new_name='vat_rate',
        ),
        migrations.RenameField(
            model_name='bestellungsposten',
            old_name='rabatt',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='bestellungsposten',
            old_name='produktpreis',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='bestellungsposten',
            old_name='menge',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='kosten',
            old_name='preis',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='kosten',
            old_name='mwstsatz',
            new_name='vat_rate',
        ),
        migrations.RenameField(
            model_name='lieferungsposten',
            old_name='menge',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='notiz',
            old_name='beschrieb',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='artikelnummer',
            new_name='article_number',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='datenblattlink',
            new_name='datasheet_url',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='beschrieb',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='bildlink',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='lieferant_artikelnummer',
            new_name='lieferant_article_number',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='mengenbezeichnung',
            new_name='quantity_description',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='verkaufspreis',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='mwstsatz',
            new_name='vat_rate',
        ),
        migrations.RenameField(
            model_name='produktkategorie',
            old_name='beschrieb',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='produktkategorie',
            old_name='bildlink',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='kurzbeschrieb',
            new_name='short_description',
        ),
    ]
