# Generated by Django 4.1.6 on 2023-02-13 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kmuhelper", "0095_rename_erstellt_am_notiz_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kunde",
            old_name="email_registriert",
            new_name="email_link_registered",
        ),
        migrations.RenameField(
            model_name="bestellung",
            old_name="kunde",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="bestellung",
            old_name="zahlungsempfaenger",
            new_name="payment_receiver",
        ),
        migrations.RenameField(
            model_name="bestellung",
            old_name="ansprechpartner",
            new_name="contact_person",
        ),
        migrations.RenameField(
            model_name="lieferant",
            old_name="ansprechpartnermail",
            new_name="contact_person_email",
        ),
        migrations.RenameField(
            model_name="lieferant",
            old_name="ansprechpartnertel",
            new_name="contact_person_phone",
        ),
        migrations.RenameField(
            model_name="lieferant",
            old_name="ansprechpartner",
            new_name="contact_person_name",
        ),
        migrations.RenameField(
            model_name="lieferant",
            old_name="adresse",
            new_name="address",
        ),
    ]
