# Generated by Django 4.1.6 on 2023-02-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "kmuhelper",
            "0096_rename_email_registriert_kunde_email_link_registered_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="language",
            field=models.CharField(
                choices=[
                    ("de", "Deutsch [DE]"),
                    ("fr", "Französisch [FR]"),
                    ("it", "Italienisch [IT]"),
                    ("en", "Englisch [EN]"),
                ],
                default="de",
                max_length=2,
                verbose_name="Sprache",
            ),
        ),
    ]
