# Generated by Django 6.0.5 on 2026-05-15 20:19

from django.db import migrations

SETTINGS = {
    "wc-url": "url",
    "wc-webhook-secret": "char",
    "email-stock-warning-receiver": "email",
    "email-show-buttons": "bool",
    "email-signature": "text",
    "default-payment-conditions": "char",
    "print-payment-conditions": "bool",
}

SECRET_SETTINGS = {
    "wc-consumer_key": "char",
    "wc-consumer_secret": "char",
    "wc-url": "url",
}


def forwards_func(apps, schema_editor):
    Setting = apps.get_model("kmuhelper", "Setting")
    SettingHidden = apps.get_model("kmuhelper", "SettingHidden")
    db_alias = schema_editor.connection.alias

    for key, value in SETTINGS.items():
        Setting.objects.using(db_alias).update_or_create(id=key, defaults={"typ": value})

    for key, value in SECRET_SETTINGS.items():
        SettingHidden.objects.using(db_alias).update_or_create(id=key, defaults={"typ": value})


class Migration(migrations.Migration):
    dependencies = [
        ("kmuhelper", "0117_alter_order_fees_alter_order_products_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
